# ============================================================
# AGENT 3: PR DESCRIPTION GENERATOR
# ============================================================
#
# Auto-generates rich PR descriptions from the code diff.
#
# HOW TO RUN:
#   PR_NUMBER=2 python scripts/pr_description_generator.py
# ============================================================

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from lib.logger import create_logger
from lib.ai_client import ask_ai
from lib.github_client import (
    get_pull_request,
    get_pr_diff,
    get_pr_files,
    add_labels,
    get_repo,
)

log = create_logger("PR-Description")

# -----------------------------------------------------------
# STEP 1: Parse PR number
# -----------------------------------------------------------
pr_number = int(os.environ.get("PR_NUMBER", 0))
if not pr_number:
    log.error("PR_NUMBER environment variable is required.")
    sys.exit(1)

log.section(f"AGENT START — PR #{pr_number} Description")

# -----------------------------------------------------------
# STEP 2: Fetch PR data
# -----------------------------------------------------------
log.info("Fetching PR details, diff, and file list...")

pr = get_pull_request(pr_number)
diff = get_pr_diff(pr_number)
files = get_pr_files(pr_number)

log.success("PR data fetched")
log.info(f"Title: {pr.title}")
log.info(f"Current description: {'exists' if pr.body else 'empty'}")
log.info(f"Files changed: {len(files)}")

# -----------------------------------------------------------
# STEP 3: Generate description with AI
# -----------------------------------------------------------
log.section("STEP 2: AI Description Generation")
log.info("Sending diff to Groq AI...")

system_prompt = """You are a technical writer who writes clear, concise PR descriptions.
Analyze the code diff and generate a professional description in Markdown.

RULES:
1. Describe WHAT changed and WHY.
2. Group changes logically.
3. Highlight breaking changes.
4. Include a testing checklist.
5. Return raw Markdown (no code fences wrapping it).

TEMPLATE:
## Summary
(1-3 sentences)

## Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Refactoring
- [ ] Documentation update

## Changes Made
(Bullet list of changes)

## Testing
- [ ] (Suggested test scenarios)

## Additional Notes
(Context or follow-up work)"""

files_list = "\n".join(
    f"- {f['filename']} (+{f['additions']} -{f['deletions']}) — {f['status']}"
    for f in files
)
user_message = f"""Generate a PR description for this Pull Request.

## PR #{pr_number}: {pr.title}
**Author:** {pr.user.login}
**Branch:** {pr.head.ref} → {pr.base.ref}
**Existing description:** {pr.body or "(empty)"}

## Changed Files:
{files_list}

## Diff:
```diff
{diff}
```

Generate the Markdown description now."""

description = ask_ai(system_prompt, user_message, temperature=0.3)
log.success("Description generated")

# -----------------------------------------------------------
# STEP 4: Update PR description on GitHub
# -----------------------------------------------------------
log.section("STEP 3: Updating PR on GitHub")
log.info("Updating PR description...")

final_body = description
if pr.body:
    final_body += f"\n\n---\n### Original Description\n{pr.body}"
final_body += "\n\n---\n🤖 *Description auto-generated by PR Description Agent using Groq AI*"

pr.edit(body=final_body)
log.success("PR description updated")

# -----------------------------------------------------------
# STEP 5: Auto-label
# -----------------------------------------------------------
log.info("Auto-labeling PR...")

auto_labels = ["ai-described"]
file_patterns = {
    "src/": "app-code",
    "test": "has-tests",
    ".github/": "ci-cd",
    "docs/": "documentation",
    "package.json": "dependencies",
    "requirements": "dependencies",
}
for f in files:
    for pattern, label in file_patterns.items():
        if pattern in f["filename"] and label not in auto_labels:
            auto_labels.append(label)

add_labels(pr_number, auto_labels)

# -----------------------------------------------------------
# DONE
# -----------------------------------------------------------
log.summary("PR Description Generator — COMPLETED", {
    "PR": f"#{pr_number} — {pr.title}",
    "Labels": ", ".join(auto_labels),
    "Description": "Updated with AI-generated content",
    "Log file": log.log_file_path,
})
